### ISSUE TITLE
make build error "cannot find package"

### ISSUE THREAD

**Issue by irthomasthomas** [RedisTimeSeries/prometheus-redistimeseries-adapter#44]
Following the instructions and running make build produces these errors: 

CGO_ENABLED=0 go build -o bin/redis_ts_adapter ./cmd/redis-ts-adapter
cmd/redis-ts-adapter/main.go:11:2: cannot find package "github.com/RedisTimeSeries/prometheus-redistimeseries-adapter/internal/redis_ts" in any of:
	/usr/lib/go-1.10/src/github.com/RedisTimeSeries/prometheus-redistimeseries-adapter/internal/redis_ts (from $GOROOT)
	/root/go/src/github.com/RedisTimeSeries/prometheus-redistimeseries-adapter/internal/redis_ts (from $GOPATH)
cmd/redis-ts-adapter/main.go:5:2: cannot find package "github.com/go-redis/redis" in any of:
	/usr/lib/go-1.10/src/github.com/go-redis/redis (from $GOROOT)
	/root/go/src/github.com/go-redis/redis (from $GOPATH)
cmd/redis-ts-adapter/main.go:12:2: cannot find package "github.com/golang/protobuf/proto" in any of:
	/usr/lib/go-1.10/src/github.com/golang/protobuf/proto (from $GOROOT)
	/root/go/src/github.com/golang/protobuf/proto (from $GOPATH)
cmd/redis-ts-adapter/main.go:13:2: cannot find package "github.com/golang/snappy" in any of:
	/usr/lib/go-1.10/src/github.com/golang/snappy (from $GOROOT)
	/root/go/src/github.com/golang/snappy (from $GOPATH)
cmd/redis-ts-adapter/main.go:14:2: cannot find package "github.com/pkg/profile" in any of:
	/usr/lib/go-1.10/src/github.com/pkg/profile (from $GOROOT)
	/root/go/src/github.com/pkg/profile (from $GOPATH)
cmd/redis-ts-adapter/main.go:15:2: cannot find package "github.com/prometheus/prometheus/prompb" in any of:
	/usr/lib/go-1.10/src/github.com/prometheus/prometheus/prompb (from $GOROOT)
	/root/go/src/github.com/prometheus/prometheus/prompb (from $GOPATH)
cmd/redis-ts-adapter/main.go:16:2: cannot find package "github.com/sirupsen/logrus" in any of:
	/usr/lib/go-1.10/src/github.com/sirupsen/logrus (from $GOROOT)
	/root/go/src/github.com/sirupsen/logrus (from $GOPATH)

**Comment by danni-m** [comment]
@irthomasthomas you need to clone the repository under
`$GOPATH/src/github.com/RedisTimeSeries` to be a able to build it.

**Comment by danni-m** [comment]
@irthomasthomas if you still having issues, please re-open.

**Comment by xQuicklyy** [comment]
jjjjjjj
